site_name: Dynatrace Managed - –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è
site_description: –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è Dynatrace Managed —Å AI-–ø–æ–º–æ—â–Ω–∏–∫–æ–º
site_author: Yerkebulan Ardabayev
site_url: https://yerkebulan-ardabayev.github.io/dynatrace-docs-website/

repo_name: dynatrace-docs-website
repo_url: https://github.com/Yerkebulan-Ardabayev/dynatrace-docs-website
edit_uri: ""

# URL configuration
use_directory_urls: true

theme:
  name: material
  language: ru
  
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: –°–≤–µ—Ç–ª–∞—è —Ç–µ–º–∞
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: –¢—ë–º–Ω–∞—è —Ç–µ–º–∞
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow
  
  icon:
    logo: material/server
    repo: fontawesome/brands/github
  
  font:
    text: Roboto
    code: JetBrains Mono

plugins:
  - search:
      lang:
        - ru
        - en

# === –ù–ê–í–ò–ì–ê–¶–ò–Ø (–∏—Å–ø—Ä–∞–≤–ª–µ–Ω–Ω–∞—è) ===
nav:
  - üè† –ì–ª–∞–≤–Ω–∞—è: index.md
  
  # MANAGED - –ì–õ–ê–í–ù–´–ô –†–ê–ó–î–ï–õ
  - üéØ Managed:
    - –û–±–∑–æ—Ä: managed/index.md
    - –£—Å—Ç–∞–Ω–æ–≤–∫–∞: managed/installation.md
    - –ù–∞—Å—Ç—Ä–æ–π–∫–∞: managed/configuration.md
    - –û–±—Å–ª—É–∂–∏–≤–∞–Ω–∏–µ: managed/operations.md
    - –û–±–Ω–æ–≤–ª–µ–Ω–∏—è: managed/update.md
    - –ë–µ–∑–æ–ø–∞—Å–Ω–æ—Å—Ç—å: managed/security.md
    - –ë—ç–∫–∞–ø: managed/backup.md
    - –ö–ª–∞—Å—Ç–µ—Ä: managed/managed-cluster.md
    - –õ–∏—Ü–µ–Ω–∑–∏—è: managed/license.md
    - API: managed/dynatrace-api/
    - –ú–æ–Ω–∏—Ç–æ—Ä–∏–Ω–≥: managed/observe/
    - –ò–Ω—Ç–µ–≥—Ä–∞—Ü–∏–∏: managed/ingest-from/
  
  # –û–ë–©–ï–ï
  - üìä –û–±—â–µ–µ:
    - –û–±–∑–æ—Ä: common/index.md
  
  # SaaS –°–ü–†–ê–í–û–ß–ù–û  
  - üìñ SaaS: saas-reference/index.md
  

  # –ü–ï–†–ï–í–ï–î–Å–ù–ù–ê–Ø –î–û–ö–£–ú–ï–ù–¢–ê–¶–ò–Ø (RU)
  - üìö –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è:
    - –û–±–∑–æ—Ä: ru/index.md
    - API Dynatrace: ru/dynatrace-api.md
    - –ò–ò Dynatrace: ru/dynatrace-intelligence.md
    - –ù–∞—á–∞–ª–æ —Ä–∞–±–æ—Ç—ã: ru/getting-started.md
    - –ò—Å—Ç–æ—á–Ω–∏–∫–∏ –¥–∞–Ω–Ω—ã—Ö: ru/ingest-from.md
    - –õ–∏—Ü–µ–Ω–∑–∏—Ä–æ–≤–∞–Ω–∏–µ: ru/license.md
    - –°–ª–æ–≤–∞—Ä—å: ru/semantic-dictionary.md
    - –ß—Ç–æ –Ω–æ–≤–æ–≥–æ: ru/whats-new.md
    - –ê–Ω–∞–ª–∏–∑ –∏ –∞–≤—Ç–æ–º–∞—Ç–∏–∑–∞—Ü–∏—è:
      - Compliance And Resilience: ru/analyze-explore-automate/compliance-and-resilience.md
      - Explorer: ru/analyze-explore-automate/explorer.md
      - –õ–æ–≥–∏: ru/analyze-explore-automate/logs.md
      - Smartscape Classic: ru/analyze-explore-automate/smartscape-classic.md
      - –î–∞—à–±–æ—Ä–¥—ã:
        - Dashboards New: ru/analyze-explore-automate/dashboards-and-notebooks/dashboards-new.md
        - –ì–æ—Ç–æ–≤—ã–µ –¥–æ–∫—É–º–µ–Ω—Ç—ã:
          - Ready Made Dashboards: ru/analyze-explore-automate/dashboards-and-notebooks/ready-made-documents/ready-made-dashboards.md
      - –õ–æ–≥–∏:
        - LMA Logs: ru/analyze-explore-automate/logs/lma-logs-app.md
        - LMA Logs:
          - Facets: ru/analyze-explore-automate/logs/lma-logs-app/facets.md
          - Limits: ru/analyze-explore-automate/logs/lma-logs-app/limits.md
          - Log Distribution Chart: ru/analyze-explore-automate/logs/lma-logs-app/log-distribution-chart.md
          - Message: ru/analyze-explore-automate/logs/lma-logs-app/message.md
          - Query And Filter: ru/analyze-explore-automate/logs/lma-logs-app/query-and-filter.md
          - Surrounding Logs: ru/analyze-explore-automate/logs/lma-logs-app/surrounding-logs.md
      - –£–≤–µ–¥–æ–º–ª–µ–Ω–∏—è:
        - Problem Notifications: ru/analyze-explore-automate/notifications-and-alerting/problem-notifications.md
    - –†–∞–∑–≤—ë—Ä—Ç—ã–≤–∞–Ω–∏–µ:
      - –ö–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏—è –∫–∞–∫ –∫–æ–¥: ru/deliver/configuration-as-code.md
      - Ownership App: ru/deliver/ownership-app.md
      - –í–ª–∞–¥–µ–Ω–∏–µ: ru/deliver/ownership.md
      - Quality Gates: ru/deliver/quality-gates.md
      - –ú–æ–Ω–∏—Ç–æ—Ä–∏–Ω–≥ —Ä–µ–ª–∏–∑–æ–≤: ru/deliver/release-monitoring.md
      - Self Service Kubernetes Use Case: ru/deliver/self-service-kubernetes-use-case.md
      - Service Level Objectives Classic: ru/deliver/service-level-objectives-classic.md
      - SLO: ru/deliver/service-level-objectives.md
      - SRG: ru/deliver/site-reliability-guardian.md
      - Test Pipeline Observability: ru/deliver/test-pipeline-observability.md
      - –ö–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏—è –∫–∞–∫ –∫–æ–¥:
        - Monaco:
          - Monaco Api Support And Access Handling: ru/deliver/configuration-as-code/monaco/monaco-api-support-and-access-handling.md
          - Monaco Concepts: ru/deliver/configuration-as-code/monaco/monaco-concepts.md
          - Monaco Getting Started: ru/deliver/configuration-as-code/monaco/monaco-getting-started.md
          - –ö–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏—è:
            - Account Configuration: ru/deliver/configuration-as-code/monaco/configuration/account-configuration.md
            - Monaco Manage Resources: ru/deliver/configuration-as-code/monaco/configuration/monaco-manage-resources.md
            - Special Configuration Types Saas: ru/deliver/configuration-as-code/monaco/configuration/special-configuration-types-saas.md
            - Yaml Configuration Saas Type Fields: ru/deliver/configuration-as-code/monaco/configuration/yaml-configuration-saas-type-fields.md
            - Yaml Configuration Saas: ru/deliver/configuration-as-code/monaco/configuration/yaml-configuration-saas.md
          - –°–ø—Ä–∞–≤–æ—á–Ω–∏–∫:
            - Commands Saas: ru/deliver/configuration-as-code/monaco/reference/commands-saas.md
        - Terraform:
          - Terraform Api Support Access Permission Handling: ru/deliver/configuration-as-code/terraform/terraform-api-support-access-permission-handling.md
          - Terraform Cli Commands: ru/deliver/configuration-as-code/terraform/terraform-cli-commands.md
          - –¢—É—Ç–æ—Ä–∏–∞–ª—ã: ru/deliver/configuration-as-code/terraform/tutorials.md
          - –¢—É—Ç–æ—Ä–∏–∞–ª—ã:
            - Terraform Tutorial Set Up Automated Notification: ru/deliver/configuration-as-code/terraform/tutorials/terraform-tutorial-set-up-automated-notification.md
      - –í–ª–∞–¥–µ–Ω–∏–µ:
        - Assign Ownership: ru/deliver/ownership/assign-ownership.md
        - Best Practices: ru/deliver/ownership/best-practices.md
        - Ownership Teams: ru/deliver/ownership/ownership-teams.md
      - Pipeline:
        - –¢—É—Ç–æ—Ä–∏–∞–ª—ã:
          - Deployment Observability Use Case Argocd: ru/deliver/pipeline-observability-sdlc-events/tutorials/deployment-observability-use-case-argocd.md
          - Pipeline Observability Tutorial Jira: ru/deliver/pipeline-observability-sdlc-events/tutorials/pipeline-observability-tutorial-jira.md
      - –ú–æ–Ω–∏—Ç–æ—Ä–∏–Ω–≥ —Ä–µ–ª–∏–∑–æ–≤:
        - Issue Tracking Integration: ru/deliver/release-monitoring/issue-tracking-integration.md
        - Monitor Releases With Dynatrace: ru/deliver/release-monitoring/monitor-releases-with-dynatrace.md
        - Version Detection Strategies: ru/deliver/release-monitoring/version-detection-strategies.md
      - SLO:
        - Create Slo: ru/deliver/service-level-objectives/create-slo.md
        - Service Level Objective Permissions: ru/deliver/service-level-objectives/service-level-objective-permissions.md
        - Service Level Objective Tile Add To Dashboard: ru/deliver/service-level-objectives/service-level-objective-tile-add-to-dashboard.md
        - Service Level Objective Tile Edit In Dashboard: ru/deliver/service-level-objectives/service-level-objective-tile-edit-in-dashboard.md
        - Service Level Objective Tile View: ru/deliver/service-level-objectives/service-level-objective-tile-view.md
        - Service Level Objective Upgrade Classic: ru/deliver/service-level-objectives/service-level-objective-upgrade-classic.md
      - Service Level Objectives Classic:
        - Slo Mz Permissions: ru/deliver/service-level-objectives-classic/slo-mz-permissions.md
      - SRG:
        - Event Structure: ru/deliver/site-reliability-guardian/event-structure.md
        - Execution Context: ru/deliver/site-reliability-guardian/execution-context.md
        - Guardian List: ru/deliver/site-reliability-guardian/guardian-list.md
    - –ó–Ω–∞–∫–æ–º—Å—Ç–≤–æ:
      - Dynatrace Apps: ru/discover-dynatrace/dynatrace-apps.md
      - Get Started: ru/discover-dynatrace/get-started.md
      - What Is Dynatrace: ru/discover-dynatrace/what-is-dynatrace.md
    - –ò–ò –∏ –∞–Ω–∞–ª–∏—Ç–∏–∫–∞:
      - –û–±–Ω–∞—Ä—É–∂–µ–Ω–∏–µ –∞–Ω–æ–º–∞–ª–∏–π: ru/dynatrace-intelligence/anomaly-detection.md
      - Copilot: ru/dynatrace-intelligence/copilot.md
      - Davis Problems: ru/dynatrace-intelligence/davis-problems-app.md
      - –ò–Ω—Ç–µ–≥—Ä–∞—Ü–∏–∏: ru/dynatrace-intelligence/dynatrace-intelligence-integrations.md
      - –ê–Ω–∞–ª–∏–∑ –ø—Ä–∏—á–∏–Ω: ru/dynatrace-intelligence/root-cause-analysis.md
      - –û–±–Ω–∞—Ä—É–∂–µ–Ω–∏–µ –∞–Ω–æ–º–∞–ª–∏–π:
        - –ù–∞—Å—Ç—Ä–æ–π–∫–∞: ru/dynatrace-intelligence/anomaly-detection/adjust-sensitivity-anomaly-detection.md
        - –ü—Ä–∏–ª–æ–∂–µ–Ω–∏–µ: ru/dynatrace-intelligence/anomaly-detection/anomaly-detection-app.md
        - Anomaly Detection Configuration: ru/dynatrace-intelligence/anomaly-detection/anomaly-detection-configuration.md
        - Auto Adaptive Threshold: ru/dynatrace-intelligence/anomaly-detection/auto-adaptive-threshold.md
        - Automated Multidimensional Baselining: ru/dynatrace-intelligence/anomaly-detection/automated-multidimensional-baselining.md
        - –ú–µ—Ç—Ä–∏–∫–∏: ru/dynatrace-intelligence/anomaly-detection/metric-events.md
        - Set Up Anomaly Detectors Via Api: ru/dynatrace-intelligence/anomaly-detection/set-up-anomaly-detectors-via-api.md
        - Static Thresholds: ru/dynatrace-intelligence/anomaly-detection/static-thresholds.md
        - –ù–∞—Å—Ç—Ä–æ–π–∫–∞:
          - Adjust Sensitivity Infastructure: ru/dynatrace-intelligence/anomaly-detection/adjust-sensitivity-anomaly-detection/adjust-sensitivity-infastructure.md
        - –ü—Ä–∏–ª–æ–∂–µ–Ω–∏–µ:
          - Anomaly Detection Status Types: ru/dynatrace-intelligence/anomaly-detection/anomaly-detection-app/anomaly-detection-status-types.md
          - Configure A Simple Ad: ru/dynatrace-intelligence/anomaly-detection/anomaly-detection-app/configure-a-simple-ad.md
          - Davis Ad Dql Best Practice: ru/dynatrace-intelligence/anomaly-detection/anomaly-detection-app/davis-ad-dql-best-practice.md
          - Davis Ad Dql Optimization: ru/dynatrace-intelligence/anomaly-detection/anomaly-detection-app/davis-ad-dql-optimization.md
        - –ú–µ—Ç—Ä–∏–∫–∏:
          - Metric Key Events: ru/dynatrace-intelligence/anomaly-detection/metric-events/metric-key-events.md
          - Metric Selector Events: ru/dynatrace-intelligence/anomaly-detection/metric-events/metric-selector-events.md
      - Copilot:
        - Chat With Davis Copilot: ru/dynatrace-intelligence/copilot/chat-with-davis-copilot.md
        - Copilot Data Privacy: ru/dynatrace-intelligence/copilot/copilot-data-privacy.md
        - Copilot Find Relevant Troubleshooting Guides: ru/dynatrace-intelligence/copilot/copilot-find-relevant-troubleshooting-guides.md
        - Copilot Getting Started: ru/dynatrace-intelligence/copilot/copilot-getting-started.md
        - Copilot Overview: ru/dynatrace-intelligence/copilot/copilot-overview.md
        - Quick Analysis Copilot Dql: ru/dynatrace-intelligence/copilot/quick-analysis-copilot-dql.md
        - Chat With Davis Copilot:
          - Copilot Conv Starters: ru/dynatrace-intelligence/copilot/chat-with-davis-copilot/copilot-conv-starters.md
        - Quick Analysis Copilot Dql:
          - Copilot Tips: ru/dynatrace-intelligence/copilot/quick-analysis-copilot-dql/copilot-tips.md
      - Davis Problems:
        - Problems App Custom Problem Field Examples: ru/dynatrace-intelligence/davis-problems-app/problems-app-custom-problem-field-examples.md
      - –ò–Ω—Ç–µ–≥—Ä–∞—Ü–∏–∏:
        - Copilot For Workflows: ru/dynatrace-intelligence/dynatrace-intelligence-integrations/copilot-for-workflows.md
        - Davis For Notebooks: ru/dynatrace-intelligence/dynatrace-intelligence-integrations/davis-for-notebooks.md
      - –°–ø—Ä–∞–≤–æ—á–Ω–∏–∫:
        - AI –º–æ–¥–µ–ª–∏: ru/dynatrace-intelligence/reference/ai-models.md
        - Davis Ai Limits: ru/dynatrace-intelligence/reference/davis-ai-limits.md
        - AI –º–æ–¥–µ–ª–∏:
          - Forecast Analysis: ru/dynatrace-intelligence/reference/ai-models/forecast-analysis.md
          - Seasonal Baseline: ru/dynatrace-intelligence/reference/ai-models/seasonal-baseline.md
      - –ê–Ω–∞–ª–∏–∑ –ø—Ä–∏—á–∏–Ω:
        - Concepts: ru/dynatrace-intelligence/root-cause-analysis/concepts.md
        - Event Analysis And Correlation: ru/dynatrace-intelligence/root-cause-analysis/event-analysis-and-correlation.md
      - –ü—Ä–∏–º–µ—Ä—ã –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è:
        - Copilot Examples: ru/dynatrace-intelligence/use-cases/copilot-examples.md
        - Copilot In Workflows Dql: ru/dynatrace-intelligence/use-cases/copilot-in-workflows-dql.md
        - Copilot In Workflows Examples: ru/dynatrace-intelligence/use-cases/copilot-in-workflows-examples.md
        - Create Alert In Logs: ru/dynatrace-intelligence/use-cases/create-alert-in-logs.md
        - Davis Dql Examples: ru/dynatrace-intelligence/use-cases/davis-dql-examples.md
        - Davis For Workflows: ru/dynatrace-intelligence/use-cases/davis-for-workflows.md
    - –ò—Å—Ç–æ—á–Ω–∏–∫–∏ –¥–∞–Ω–Ω—ã—Ö:
      - Extensions: ru/ingest-from/extensions.md
      - OneAgent:
        - Installation And Operation: ru/ingest-from/dynatrace-oneagent/installation-and-operation.md
    - –õ–∏—Ü–µ–Ω–∑–∏—Ä–æ–≤–∞–Ω–∏–µ:
      - Account Management Api: ru/license/account-management-api.md
      - Billing Reports: ru/license/billing-reports.md
      - Budget Alerts: ru/license/budget-alerts.md
      - –í–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏: ru/license/capabilities.md
      - Cost Monitors: ru/license/cost-monitors.md
      - Dps First Year: ru/license/dps-first-year.md
      - Dps Permissions: ru/license/dps-permissions.md
      - License Lifecycle: ru/license/license-lifecycle.md
      - Monitoring Consumption Classic: ru/license/monitoring-consumption-classic.md
      - –í–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏:
        - Log Analytics:
          - Dps Log Query: ru/license/capabilities/log-analytics/dps-log-query.md
    - –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ:
      - Hub: ru/manage/hub.md
    - Managed:
      - –û–±–∑–æ—Ä: ru/managed/index.md
    - –ú–æ–Ω–∏—Ç–æ—Ä–∏–Ω–≥:
      - Digital Experience: ru/observe/digital-experience.md
      - Dynatrace For Ai Observability: ru/observe/dynatrace-for-ai-observability.md
      - –ò–Ω—Ñ—Ä–∞—Å—Ç—Ä—É–∫—Ç—É—Ä–∞: ru/observe/infrastructure-observability.md
      - –ü—Ä–∏–ª–æ–∂–µ–Ω–∏—è:
        - Distributed Tracing: ru/observe/application-observability/distributed-tracing.md
        - –°–µ—Ä–≤–∏—Å—ã:
          - Services App: ru/observe/application-observability/services/services-app.md
      - Digital Experience:
        - –°–∏–Ω—Ç–µ—Ç–∏–∫–∞:
          - Synthetic on Grail:
            - Synthetic App: ru/observe/digital-experience/synthetic-monitoring/synthetic-on-grail/synthetic-app.md
      - –ò–Ω—Ñ—Ä–∞—Å—Ç—Ä—É–∫—Ç—É—Ä–∞:
        - Infrastructure And Operations: ru/observe/infrastructure-observability/infrastructure-and-operations.md
        - –û–±–ª–∞–∫–æ:
          - Clouds App: ru/observe/infrastructure-observability/cloud-platform-monitoring/clouds-app.md
        - Kubernetes:
          - Kubernetes App: ru/observe/infrastructure-observability/container-platform-monitoring/kubernetes-app.md
          - Kubernetes Monitoring: ru/observe/infrastructure-observability/container-platform-monitoring/kubernetes-monitoring.md
          - Kubernetes App:
            - Enable K8S Experience:
              - Existing Clusters: ru/observe/infrastructure-observability/container-platform-monitoring/kubernetes-app/enable-k8s-experience/existing-clusters.md
            - Preview:
              - Enhanced Object Vis Preview: ru/observe/infrastructure-observability/container-platform-monitoring/kubernetes-app/preview/enhanced-object-vis-preview.md
            - –°–ø—Ä–∞–≤–æ—á–Ω–∏–∫:
              - Permissions: ru/observe/infrastructure-observability/container-platform-monitoring/kubernetes-app/reference/permissions.md
        - –ë–∞–∑—ã –¥–∞–Ω–Ω—ã—Ö:
          - Database App: ru/observe/infrastructure-observability/databases/database-app.md
    - –ü–ª–∞—Ç—Ñ–æ—Ä–º–∞:
      - Appengine: ru/platform/appengine.md
      - Oneagent: ru/platform/oneagent.md
      - Openpipeline: ru/platform/openpipeline.md
      - Grail:
        - Dynatrace Grail: ru/platform/grail/dynatrace-grail.md
        - Dynatrace Query Language: ru/platform/grail/dynatrace-query-language.md
    - –ë–µ–∑–æ–ø–∞—Å–Ω–æ—Å—Ç—å:
      - –£–≥—Ä–æ–∑—ã: ru/secure/threat-observability.md
      - –£–≥—Ä–æ–∑—ã:
        - Security Events Ingest: ru/secure/threat-observability/security-events-ingest.md
    - –ß—Ç–æ –Ω–æ–≤–æ–≥–æ:
      - Activegate: ru/whats-new/activegate.md
      - Oneagent: ru/whats-new/oneagent.md
      - Saas: ru/whats-new/saas.md

  # AI
  - ü§ñ AI: ai/groq.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - tables

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/groq-chat.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Yerkebulan-Ardabayev

copyright: ¬© 2026 Dynatrace Managed Docs
